### ISSUE TITLE
Build instruction missing

### ISSUE THREAD

**Issue by ataffanel** [theseankelly/crazyflie2-windows-uap-client#1]
I tried to compile this project with VisualStudio 2015 community but VS refused to open the project. What version of VS is required and with what install options?

It would be nice to add build instruction to the readme file (I can contribute it when I manage to compile :).

**Comment by theseankelly** [comment]
Hey Arnaud -- I just pushed a commit to fix the csproj file.  It had a couple files which aren't part of source control, so building fails.  These files didn't need to be part of the csproj file, so I've removed them.

Either way, this problem wouldn't have caused the project to fail to load in VS.  What errors are you seeing when you double click the csproj file?

**Comment by ataffanel** [comment]
Hi Sean, it worked after I reinstalled VS2015 Commuity. the error was about VS not having the right component to build the projects (and no solution was available, just closing). I reinstalled with default settings and when I opened the project VS launched the installer to install the rest.
